apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-subs
  namespace:  openshift-storage 
spec:
  channel: stable-${odf_version}
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace